wav_hist = executable(
  'wav_hist',
  'wav_hist.c',
  'hist_plot.c',
  'wav.c',
  install: true,
)

wav_quant = executable(
  'wav_quant',
  'wav_quant.c',
  'wav.c',
  install: true,
)

wav_cmp = executable(
  'wav_cmp',
  'wav_cmp.c',
  'wav.c',
  dependencies: m_dep,
  install: true,
)

wav_effects = executable(
  'wav_effects',
  'wav_effects.c',
  'wav.c',
  dependencies: m_dep,
  install: true,
)